from dataclasses import dataclass
from swagger_codegen_fork.api.client import ApiClient
from swagger_codegen_fork.api.configuration import Configuration
from swagger_codegen_fork.api.adapter.base import HttpClientAdapter


from .apis.charge_history.api import ChargeHistoryApi

from .apis.charger.api import ChargerApi

from .apis.charger_firmware.api import ChargerFirmwareApi

from .apis.constants.api import ConstantsApi

from .apis.installation.api import InstallationApi

from .apis.session.api import SessionApi

from .apis.user_group.api import UserGroupApi



@dataclass
class AutogeneratedApiClient:
    configuration: Configuration
    client: ApiClient
    charge_history: ChargeHistoryApi
    charger: ChargerApi
    charger_firmware: ChargerFirmwareApi
    constants: ConstantsApi
    installation: InstallationApi
    session: SessionApi
    user_group: UserGroupApi


def new_client(
    adapter: HttpClientAdapter, configuration: Configuration
) -> AutogeneratedApiClient:
    client = ApiClient(configuration=configuration, adapter=adapter)
    return AutogeneratedApiClient(
        configuration,
        client=client,
        
        charge_history=ChargeHistoryApi(client, configuration),
        
        charger=ChargerApi(client, configuration),
        
        charger_firmware=ChargerFirmwareApi(client, configuration),
        
        constants=ConstantsApi(client, configuration),
        
        installation=InstallationApi(client, configuration),
        
        session=SessionApi(client, configuration),
        
        user_group=UserGroupApi(client, configuration)
        
    )